f = 1
CLS
s = 1



5 IF s + x = 0 THEN END
IF s = 60 THEN END
COLOR 15
FOR t = 1 TO 20
LOCATE 20, s + x
PRINT CHR$(219)
x = x + 1
NEXT t

LOCATE f, 34
PRINT CHR$(219)
f = f + 1
IF f = 23 THEN PRINT "caca"





IF s > 34 AND f = 21 THEN END



a$ = INPUT$(1)
x = 1
COLOR 0
LOCATE f - 1, 34
PRINT CHR$(219)
FOR t = 1 TO 31
LOCATE 20, x + s - 1
PRINT CHR$(219)
x = x + 1
NEXT t
x = 1
IF a$ = "a" THEN s = s - 2
IF a$ = "¤" THEN s = s + 2
IF a$ = " " THEN END

GOTO 5

