








































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































CLS
PRINT "CODE ENTRE :"
PRINT "PISTA = DATA DE NAIXEMENT DEL CREADOR A'AQUEST JOC"
PRINT "PISTA = EL NOMBRE QUE DIVIDIT PER 4 DONA L'ARREL QUADRADA"
PRINT "        DEL NOMBRE QUE ELEVAT A ELL MATEIX MULTIPLICAT"
PRINT "        PER LA DIVISIO DEL DOBLE DEL QUOCIENT DE LA RESTA"
PRINT "        DE LA DISTANCIA QUE HI HA DE L'ESCOLA FINS A LA "
PRINT "        PLATJA D'INDONESIA PASSANT PER MÔXIC I FENT ESCALA"
PRINT "        A GRAN BRETANYA MES EL TER€ DE LA MEITAT DE L'ARREL"
PRINT "        QUADRADA DE 423566724765735671346"
PRINT "PISTA = XUF"
A$ = INPUT$(3)
IF A$ = "JBV" THEN 1
CLS
PRINT " AQUEST NO ES EL CODI CAPULLU"
A$ = INPUT$(1)
END

1






SCREEN 13
A = 70
B = 35
W = 7
xx = 7
xxX = 7
XXXX = 7
xxxxx = 7
xxxxxx = 7
xxxxxxx = 7
xxxxxxxx = 7
xxxxxxxxx = 7
5 VIEW (0, 0)-(300, 170), 22


LINE (3, 132)-(3, 138), 14
LINE (3, 132)-(6, 132), 14
LINE (7, 133)-(7, 137), 14
LINE (3, 138)-(6, 138), 14
LINE (9, 135)-(9, 137), W
LINE (10, 134)-(11, 134), W
LINE (12, 135)-(12, 137), W
LINE (10, 138)-(11, 138), W
LINE (14, 134)-(14, 138), W
PSET (15, 135), W
PSET (16, 134), W
LINE (17, 135)-(17, 138), W
PSET (19, 137), W
LINE (20, 134)-(21, 134), W
LINE (20, 136)-(21, 136), W
LINE (20, 138)-(21, 138), W
LINE (22, 135)-(22, 137), W
PSET (23, 138), W
LINE (25, 134)-(25, 138), W
PSET (26, 135), W
LINE (27, 134)-(28, 134), W

LINE (3, 147)-(3, 151), 14
LINE (4, 146)-(6, 146), 14
LINE (7, 147)-(7, 151), 14
LINE (4, 152)-(6, 152), 14
LINE (9, 146)-(9, 152), xx
LINE (10, 148)-(11, 148), xx
LINE (12, 149)-(12, 151), xx
PSET (11, 152), xx
PSET (10, 151), xx
LINE (14, 148)-(14, 152), xx
PSET (15, 149), xx
LINE (16, 148)-(17, 148), xx
LINE (19, 148)-(20, 148), xx
LINE (20, 148)-(20, 152), xx
LINE (19, 152)-(21, 152), xx
PSET (20, 146), xx
LINE (23, 148)-(23, 152), xx
PSET (24, 149), xx
LINE (25, 148)-(26, 148), xx

LINE (3, 165)-(3, 159), xxX
LINE (3, 159)-(6, 162), xxX
LINE (6, 162)-(9, 159), xxX
LINE (9, 159)-(9, 165), xxX
LINE (11, 165)-(13, 165), 14
LINE (12, 161)-(12, 165), 14
PSET (11, 161), 14
PSET (12, 159), 14
LINE (15, 161)-(15, 165), xxX
PSET (16, 162), xxX
LINE (17, 161)-(18, 161), xxX
PSET (20, 164), xxX
LINE (21, 161)-(22, 161), xxX
LINE (21, 163)-(22, 163), xxX
LINE (21, 165)-(22, 165), xxX
LINE (23, 162)-(23, 164), xxX
PSET (24, 165), xxX
LINE (26, 161)-(26, 165), xxX
PSET (27, 162), xxX
LINE (28, 161)-(29, 161), xxX

LINE (40, 132)-(40, 138), XXXX
LINE (40, 132)-(43, 132), XXXX
LINE (40, 135)-(42, 135), XXXX
LINE (40, 138)-(43, 138), XXXX
LINE (45, 134)-(45, 138), 14
PSET (46, 135), 14
PSET (47, 134), 14
LINE (48, 135)-(48, 138), 14
LINE (50, 134)-(50, 138), XXXX
PSET (51, 135), XXXX
LINE (52, 134)-(53, 134), XXXX
PSET (54, 137), XXXX
LINE (55, 134)-(56, 134), XXXX
LINE (55, 136)-(56, 136), XXXX
LINE (55, 138)-(56, 138), XXXX
LINE (57, 135)-(57, 137), XXXX
PSET (58, 138), XXXX
LINE (60, 135)-(60, 137), XXXX
LINE (61, 134)-(62, 134), XXXX
LINE (61, 138)-(62, 138), XXXX
LINE (63, 135)-(63, 137), XXXX
LINE (65, 134)-(65, 138), XXXX
PSET (66, 135), XXXX
PSET (67, 134), XXXX
LINE (68, 135)-(68, 138), XXXX
PSET (70, 137), XXXX
LINE (71, 134)-(72, 134), XXXX
LINE (71, 136)-(72, 136), XXXX
LINE (71, 138)-(72, 138), XXXX
LINE (73, 135)-(73, 137), XXXX
PSET (74, 138), XXXX
LINE (76, 134)-(76, 138), XXXX
PSET (77, 135), XXXX
LINE (78, 134)-(79, 134), XXXX
 
LINE (42, 146)-(42, 152), 14
LINE (40, 146)-(44, 146), 14
PSET (45, 151), xxxxx
LINE (46, 148)-(47, 148), xxxxx
LINE (46, 150)-(47, 150), xxxxx
LINE (46, 152)-(47, 152), xxxxx
LINE (48, 149)-(48, 151), xxxxx
PSET (49, 152), xxxxx
LINE (51, 148)-(51, 152), xxxxx
PSET (52, 149), xxxxx
PSET (53, 148), xxxxx
LINE (54, 149)-(54, 152), xxxxx
LINE (56, 149)-(56, 151), xxxxx
LINE (57, 148)-(58, 148), xxxxx
LINE (57, 152)-(58, 152), xxxxx
PSET (60, 151), xxxxx
LINE (61, 148)-(62, 148), xxxxx
LINE (61, 150)-(62, 150), xxxxx
LINE (61, 152)-(62, 152), xxxxx
LINE (63, 149)-(63, 151), xxxxx
PSET (64, 152), xxxxx
LINE (66, 148)-(66, 152), xxxxx
PSET (67, 149), xxxxx
LINE (68, 148)-(69, 148), xxxxx

LINE (40, 159)-(43, 159), 14
LINE (40, 159)-(40, 165), 14
LINE (40, 162)-(42, 162), 14
LINE (40, 165)-(42, 165), 14
LINE (45, 161)-(45, 165), xxxxxx
PSET (46, 161), xxxxxx
LINE (47, 162)-(47, 165), xxxxxx
LINE (48, 161)-(49, 161), xxxxxx
LINE (50, 162)-(50, 165), xxxxxx
LINE (52, 166)-(52, 161), xxxxxx
PSET (53, 163), xxxxxx
PSET (54, 164), xxxxxx
LINE (52, 161)-(54, 161), xxxxxx
LINE (55, 162)-(55, 163), xxxxxx
LINE (57, 161)-(57, 164), xxxxxx
LINE (60, 161)-(60, 165), xxxxxx
PSET (58, 165), xxxxxx
PSET (59, 164), xxxxxx
LINE (63, 159)-(63, 165), xxxxxx
LINE (62, 160)-(64, 160), xxxxxx
LINE (66, 161)-(70, 165), xxxxxx
LINE (66, 165)-(70, 161), xxxxxx
PSET (72, 164), xxxxxx


LINE (73, 161)-(74, 161), xxxxxx
LINE (73, 163)-(74, 163), xxxxxx
LINE (73, 165)-(74, 165), xxxxxx
LINE (75, 162)-(75, 164), xxxxxx
PSET (76, 165), xxxxxx
LINE (78, 161)-(78, 165), xxxxxx
PSET (79, 162), xxxxxx
LINE (80, 161)-(81, 161), xxxxxx
LINE (91, 132)-(91, 137), 14
LINE (92, 138)-(94, 138), 14
LINE (95, 132)-(95, 137), 14
LINE (97, 138)-(99, 138), xxxxxxx
PSET (100, 137), xxxxxxx
LINE (98, 136)-(99, 136), xxxxxxx
PSET (97, 135), xxxxxxx
LINE (98, 134)-(100, 134), xxxxxxx
PSET (102, 137), xxxxxxx
LINE (103, 138)-(104, 138), xxxxxxx
LINE (103, 136)-(104, 136), xxxxxxx
LINE (103, 134)-(104, 134), xxxxxxx
LINE (105, 135)-(105, 137), xxxxxxx
PSET (106, 138), xxxxxxx
LINE (108, 134)-(108, 138), xxxxxxx
PSET (109, 135), xxxxxxx
LINE (110, 134)-(111, 134), xxxxxxx

LINE (91, 146)-(91, 152), 14
LINE (92, 146)-(95, 146), 14
LINE (95, 146)-(95, 152), 14
LINE (91, 149)-(95, 149), 14
LINE (97, 153)-(99, 153), xxxxxxxx
LINE (100, 149)-(100, 152), xxxxxxxx
PSET (98, 151), xxxxxxxx
PSET (99, 150), xxxxxxxx
LINE (97, 149)-(97, 150), xxxxxxxx
LINE (98, 148)-(99, 148), xxxxxxxx
PSET (102, 151), xxxxxxxx
LINE (103, 148)-(104, 148), xxxxxxxx
LINE (103, 150)-(104, 150), xxxxxxxx
LINE (103, 152)-(104, 152), xxxxxxxx
LINE (105, 149)-(105, 151), xxxxxxxx
PSET (106, 152), xxxxxxxx
LINE (108, 149)-(108, 152), xxxxxxxx
LINE (109, 148)-(110, 148), xxxxxxxx
PSET (109, 150), xxxxxxxx
PSET (112, 151), xxxxxxxx
LINE (113, 148)-(114, 148), xxxxxxxx
LINE (113, 150)-(114, 150), xxxxxxxx
LINE (113, 152)-(114, 152), xxxxxxxx
LINE (115, 149)-(115, 151), xxxxxxxx
PSET (116, 152), xxxxxxxx
LINE (118, 148)-(118, 152), xxxxxxxx
PSET (119, 149), xxxxxxxx

LINE (120, 148)-(121, 148), xxxxxxxx

LINE (90, 159)-(90, 165), 14
LINE (90, 159)-(93, 162), 14
LINE (93, 162)-(96, 159), 14
LINE (96, 159)-(96, 165), 14
PSET (98, 164), xxxxxxxxx
LINE (99, 161)-(100, 161), xxxxxxxxx
LINE (99, 163)-(100, 163), xxxxxxxxx
LINE (99, 165)-(100, 165), xxxxxxxxx
LINE (101, 162)-(101, 164), xxxxxxxxx
PSET (102, 165), xxxxxxxxx
LINE (104, 159)-(104, 165), xxxxxxxxx
LINE (103, 160)-(105, 160), xxxxxxxxx
PSET (106, 164), xxxxxxxxx
LINE (107, 161)-(108, 161), xxxxxxxxx
LINE (107, 163)-(108, 163), xxxxxxxxx
LINE (107, 165)-(108, 165), xxxxxxxxx
LINE (109, 162)-(109, 164), xxxxxxxxx
PSET (110, 165), xxxxxxxxx
LINE (112, 161)-(112, 165), xxxxxxxxx
PSET (113, 162), xxxxxxxxx
LINE (114, 161)-(115, 161), xxxxxxxxx
W = 7
xx = 7
xxX = 7
XXXX = 7
xxxxx = 7
xxxxxx = 7
xxxxxxx = 7
xxxxxxxx = 7
xxxxxxxxx = 7
i = 23
2 LINE (161, 136)-(166, 131), i
LINE (166, 131)-(171, 136), i
LINE (161, 136)-(164, 136), i
LINE (171, 136)-(168, 136), i
LINE (164, 136)-(164, 145), i
LINE (168, 136)-(168, 145), i
LINE (164, 145)-(168, 145), i
LINE (164, 151)-(168, 151), i
LINE (164, 151)-(164, 160), i
LINE (168, 151)-(168, 160), i
LINE (164, 160)-(161, 160), i
LINE (161, 160)-(166, 165), i
LINE (168, 160)-(171, 160), i
LINE (171, 160)-(166, 165), i

sen = 24
LINE (1, 167)-(129, 167), sen
LINE (1, 141)-(129, 155), sen, B
LINE (34, 131)-(34, 167), sen
LINE (84, 131)-(84, 167), sen
LINE (129, 131)-(129, 167), sen
LINE (1, 131)-(1, 167), 22
PSET (1, 141), sen
PSET (1, 155), sen
PSET (1, 167), sen
LINE (0, 130)-(130, 168), 0, B
LINE (0, 142)-(130, 156), 0, B
LINE (35, 130)-(85, 168), 0, B
LINE (180, 130)-(292, 168), 0, B
LINE (181, 148)-(291, 148), sen
LINE (181, 167)-(291, 167), sen
LINE (181 + 26, 131)-(181 + 26, 167), sen
LINE (181 + 28 + 26, 131)-(181 + 26 + 28, 167), sen
LINE (181 + 28 + 28 + 26, 131)-(181 + 27 + 27 + 28, 167), sen
LINE (181 + (28 * 3) + 26, 131)-(181 + (28 * 3) + 26, 167), sen
LINE (180, 149)-(292, 149), 0
LINE (208, 130)-(208 + 28, 168), 0, B
LINE (208 + 84, 130)-(208 + 56, 168), 0, B


LINE (0, 0)-(300, 110), 0, BF
LINE (0, 110)-(300, 125), 25, BF
LINE (1, 111)-(299, 124), 0, BF
LINE (1, 126)-(300, 126), sen
LINE (1, 124)-(300, 124), sen
LINE (154, 126)-(154, 169), sen
LINE (176, 126)-(176, 169), sen
LINE (0, 125)-(300, 170), 0, B
LINE (177, 125)-(155, 170), 0, B
LINE (0, 0)-(300, 109), 19, B
IF HAB = 10 THEN RETURN

COLOR 4
LOCATE 6, 13
PRINT "INDIANA JONES"
LOCATE 8, 13
PRINT "    I LA"
LOCATE 10, 13
PRINT "ULTIMA CRUZADA 2"
GOSUB 1000
A$ = INPUT$(1)
A = 160
10 LINE (1, 1)-(299, 108), 42, BF
7 LINE (1, 50)-(100, 80), 42, BF
LINE (1, 100)-(50, 70), 0
LINE (50, 70)-(50, 10), 0
LINE (50, 10)-(10, 1), 0
LINE (50, 70)-(100, 70), 0
LINE (140, 25)-(145, 20), 0
LINE (140, 75)-(145, 70), 0
LINE (145, 20)-(145, 70), 0
LINE (100, 25)-(105, 20), 0
LINE (105, 20)-(145, 20), 0


LINE (100, 25)-(140, 75), 0, B
LINE (101, 26)-(139, 74), 43, BF
LINE (103, 28)-(137, 50), 0, B
LINE (104, 29)-(136, 49), 112, BF
LINE (104, 29)-(110, 49), 114, BF
LINE (104, 49)-(136, 44), 114, BF
LINE (110, 28)-(137, 44), 0, B
LINE (103, 50)-(110, 44), 0
LINE (102, 24)-(140, 24), 113
LINE (103, 23)-(141, 23), 113
LINE (104, 22)-(142, 22), 113
LINE (105, 21)-(143, 21), 113
LINE (141, 25)-(141, 73), 114
LINE (142, 24)-(142, 72), 114
LINE (143, 23)-(143, 71), 114

LINE (144, 22)-(144, 70), 114
IF CALAIX = 0 THEN GOSUB 9
IF CALAIX = 10 THEN GOSUB 8
LINE (60, 25)-(90, 50), 0, B
LINE (61, 26)-(64, 49), 112, BF
LINE (61, 49)-(89, 46), 112, BF
PSET (62, 48), 0
PSET (61, 49), 0
PSET (63, 47), 0
PSET (64, 46), 0
LINE (146, 70)-(230, 70), 0
LINE (230, 70)-(299, 101), 0
LINE (230, 70)-(230, 9), 0
LINE (230, 9)-(285, 1), 0
LINE (230, 9)-(50, 10), 0
LINE (240, 25)-(240, 50), 0
LINE (240, 25)-(255, 20), 0
LINE (240, 50)-(255, 55), 0
LINE (255, 55)-(255, 20), 0
LINE (240, 50)-(245, 50), 0
LINE (245, 50)-(245, 23), 0
LINE (246, 50)-(255, 53), 0
LINE (244, 51)-(246, 51), 112
LINE (247, 52)-(249, 52), 112
LINE (250, 53)-(252, 53), 112
LINE (253, 54)-(254, 54), 112
LINE (241, 25)-(243, 49), 113, BF
LINE (244, 24)-(244, 49), 113
LINE (246, 24)-(254, 49), 11, BF
LINE (247, 50)-(254, 23), 11, BF
LINE (250, 51)-(254, 22), 11, BF
LINE (253, 52)-(254, 21), 11, BF
IF MAPA = 20 THEN LINE (185, 132)-(200, 146), 43, BF
IF MAPA = 20 THEN LINE (188, 143)-(190, 145), 4
IF MAPA = 20 THEN LINE (188, 145)-(190, 143), 4
IF X = 100 THEN 13
LINE (65, 26)-(89, 45), 11, BF
LOCATE 15, 2
IF X = 1000 THEN 31
GOSUB 1000
IF MAPA = 10 THEN PRINT "HI HA UN MAPA                    "
IF A > 220 AND B > 20 AND A < 232 AND A > 32 THEN PRINT "TIRAR-SE PER LA FINESTRA ?"
IF A = 68 AND B = 24 THEN PRINT "TIRAR-SE PER LA FINESTRA ?"
IF OBRIR = 10 AND A > 90 AND A < 140 AND B < 33 THEN PRINT "OBRIR CALAIX       "
LOCATE 15, 2
IF TANCAR = 10 AND A > 90 AND A < 140 AND B < 33 THEN PRINT "TANCAR CALAIX        "
LOCATE 15, 2
IF MIRAR = 10 AND A > 90 AND A < 140 AND B < 33 AND MAPA = 0 THEN PRINT "MIRAR CALAIX        "
LOCATE 15, 2
IF AGAFAR = 10 AND A > 90 AND A < 140 AND B < 33 AND MAPA = 10 THEN PRINT "AGAFAR MAPA        "

IF X = 1000 THEN 31
A$ = INPUT$(1)
LOCATE 15, 2
PRINT "                              "
IF A$ = "4" THEN A = A - 4
IF A$ = "6" THEN A = A + 4
IF A$ = "8" THEN B = B - 4
IF A$ = "2" THEN B = B + 4
IF A$ = "E" THEN END
IF B > 60 THEN B = 60
IF A < 0 THEN A = 0
IF B < 45 AND A < 4 THEN A = 16
IF B < 41 AND A < 20 THEN A = 20
IF B < 37 AND A < 28 THEN A = 28
IF B < 33 AND A < 32 THEN A = 32
IF B < 29 AND A < 40 THEN A = 40
IF B < 25 AND A < 44 THEN A = 44
IF B < 24 THEN B = 24
IF A > 90 AND A < 140 AND B < 28 THEN B = 28
IF A > 80 AND A < 140 AND B < 25 THEN A = 80
IF A > 280 THEN A = 280
IF A > 276 AND B < 49 THEN A = 264
IF A > 256 AND B < 45 THEN A = 256
IF A > 244 AND B < 41 THEN A = 244
IF A > 236 AND B < 37 THEN A = 236
IF A > 228 AND B < 33 THEN A = 228
IF A > 220 AND B < 29 THEN A = 220
IF A > 212 AND B < 25 THEN A = 212
IF A > 90 AND A < 140 AND B < 33 AND TANCAR = 10 AND OBRIR = 0 AND A$ = " " AND CALAIX = 10 THEN CALAIX = 0
IF A > 90 AND A < 140 AND B < 33 AND TANCAR = 0 AND OBRIR = 10 AND A$ = " " AND CALAIX = 0 THEN CALAIX = 10
IF CALAIX = 10 AND MIRAR = 10 AND A > 90 AND A < 140 AND B < 33 AND A$ = " " THEN MAPA = 10
IF MAPA = 10 AND AGAFAR = 10 AND A > 90 AND A < 140 AND B < 33 AND CALAIX = 10 AND A$ = " " THEN MAPA = 20






IF A > 220 AND B > 20 AND A < 232 AND B < 36 AND A$ = " " THEN 30
IF A = 68 AND B = 24 AND A$ = " " THEN INDY = 10
IF A = 68 AND B = 24 AND A$ = " " THEN GOTO 1000
OBRIR = 0
TANCAR = 0
MIRAR = 0
AGAFAR = 0
IF A$ = "O" THEN OBRIR = 10
IF A$ = "T" THEN TANCAR = 10
IF A$ = "A" THEN AGAFAR = 10
IF A$ = "I" THEN MIRAR = 10
GOTO 10

30 LOCATE 15, 2
PRINT "SI TU M'HO DIUS..."
FOR T = 1 TO 11000: NEXT T
X = 1000
GOTO 10
31 PRINT "HAAAAAAA....          "
GOTO 40
END
20 LOCATE 15, 2
PRINT " HO HO...                         "
FOR T = 1 TO 7000: NEXT T
LOCATE 15, 2
PRINT "HAAAAAAAAAA....                   "
LINE (65, 26)-(89, 45), 11, BF
FOR T = 1 TO 10000: NEXT T
LOCATE 15, 2
PRINT "             ­  C R A X  !        "
GOTO 10001
END


END
9 LINE (103, 55)-(137, 61), 0, B
LINE (104, 56)-(136, 60), 113, BF
PSET (120, 57), 0
PSET (119, 58), 0
PSET (121, 58), 0
PSET (120, 59), 0
PSET (120, 58), 114
RETURN
8 LINE (103, 55)-(137, 61), 0, BF
LINE (102, 58)-(138, 64), 0, B
LINE (103, 59)-(137, 63), 113, BF
PSET (120, 60), 0
PSET (119, 61), 0
PSET (121, 61), 0
PSET (120, 62), 0
PSET (120, 61), 114
RETURN



40 B = -70
DIN = 2
A = 160
DINERS = 0
FOR T = 1 TO 15000: NEXT T
41
LOCATE 15, 2
PRINT "             "
LINE (1, 1)-(299, 109), 0, BF
LINE (1, 1)-(299, 70), 42, BF
LINE (1, 71)-(299, 71), 0
LINE (1, 72)-(299, 85), 23, BF
LINE (1, 86)-(299, 86), 0
LINE (1, 87)-(299, 89), 21, BF
LINE (1, 90)-(299, 90), 0
LINE (1, 91)-(299, 109), 19, BF
LINE (30, 71)-(60, 25), 0, B
LINE (31, 70)-(59, 26), 43, B
LINE (32, 69)-(58, 27), 43, B
IF PORTA = 0 THEN LINE (33, 70)-(57, 28), 113, BF
IF PORTA = 20 THEN LINE (33, 70)-(57, 28), 0, BF
LINE (23, 15)-(70, 24), 0, BF
LINE (23, 24)-(70, 14), 1, B
LOCATE 3, 5
PRINT "SHOP"
IF BITLLET = 20 THEN DIN = 23
LINE (230, 80)-(235, 82), DIN, BF
LINE (229, 80)-(229, 81), DIN
PSET (228, 80), DIN
LINE (236, 81)-(236, 82), DIN
PSET (237, 82), DIN
IF BITLLET = 20 THEN GOSUB 9000
GOSUB 1000
IF l = 0 THEN 44
LOCATE 15, 2
PRINT "                           "
LOCATE 15, 2
IF A > 210 AND A < 250 AND B < 38 AND BITLLET = 0 AND AGAFAR = 10 THEN PRINT "AGAFAR BITLLET"
IF A > 210 AND A < 250 AND B < 38 AND BITLLET = 0 AND AGAFAR = 10 THEN BITLLET = 10
IF ATROP = 10 THEN PRINT "NO VULL QUE M'ATROPELLIN"
IF A > 25 AND A < 45 AND B < 31 AND OBRIR = 10 THEN PRINT "OBRIR PORTA"
IF A > 25 AND A < 45 AND B < 31 AND TANCAR = 10 THEN PRINT "TANCAR PORTA"
A$ = INPUT$(1)
IF A > 25 AND A < 45 AND B < 27 AND PORTA = 20 AND A$ = "8" THEN 50
ATROP = 0

IF A$ = "6" THEN A = A + 4
IF A$ = "4" THEN A = A - 4
IF A$ = "8" THEN B = B - 4
IF A$ = "2" THEN B = B + 4
IF B = 38 AND A$ = "2" THEN ATROP = 10
IF B = 42 THEN B = 38
IF B < 26 THEN B = 26
IF A$ = "E" THEN END
IF A$ = " " AND BITLLET = 10 THEN BITLLET = 20
IF A$ = " " AND OBRIR = 10 THEN PORTA = 20
IF A$ = " " AND TANCAR = 10 THEN PORTA = 0
OBRIR = 0
TANCAR = 0
AGAFAR = 0
IF A$ = "T" THEN TANCAR = 10
IF A$ = "O" THEN OBRIR = 10
IF A$ = "A" THEN AGAFAR = 10
GOTO 41
44 B = B + 6
FOR T = 1 TO 200: NEXT T
IF B > 30 THEN B = 30
IF B = 30 THEN l = 10
GOTO 41


50 A = 34
B = 36
51
LINE (1, 1)-(299, 109), 24, BF
LINE (0, 15)-(75, 25), 0
LINE (75, 25)-(75, 65), 0
LINE (0, 100)-(75, 65), 0
LINE (75, 25)-(200, 25), 0
LINE (200, 25)-(299, 15), 0
LINE (75, 65)-(200, 65), 0
LINE (200, 65)-(299, 100), 0
LINE (200, 25)-(200, 65), 0
LINE (33, 85)-(33, 40), 0
LINE (44, 80)-(44, 35), 0
LINE (44, 35)-(33, 40), 0
LINE (34, 39)-(35, 84), 0, BF
LINE (36, 38)-(37, 83), 0, BF
LINE (38, 37)-(40, 82), 0, BF
LINE (41, 36)-(42, 81), 0, BF
LINE (43, 35)-(43, 80), 0
GOSUB 28
IF A > 185 AND A < 211 AND B = 36 THEN TAULELL = 10
IF A > 193 AND A < 211 AND B = 40 THEN TAULELL = 10
IF A > 177 AND A < 211 AND B = 32 THEN TAULELL = 10
IF A > 167 AND A < 211 AND B = 28 THEN TAULELL = 10
IF A > 161 AND A < 211 AND B = 24 THEN TAULELL = 10
IF A > 150 AND A < 211 AND B = 20 THEN TAULELL = 10


IF TAULELL = 10 THEN GOSUB 1000
LINE (150, 65)-(150, 50), 0
LINE (150, 65)-(200, 90), 0
LINE (200, 90)-(210, 75), 0, B
LINE (150, 50)-(200, 75), 0
LINE (150, 50)-(160, 50), 0
LINE (160, 50)-(210, 75), 0
LINE (160, 51)-(206, 74), 112
LINE (159, 51)-(205, 74), 112
LINE (158, 51)-(204, 74), 112
LINE (157, 51)-(203, 74), 112
LINE (156, 51)-(202, 74), 112
LINE (155, 51)-(201, 74), 112
LINE (154, 51)-(200, 74), 112
PSET (153, 51), 112
LINE (151, 52)-(152, 65), 113, BF
LINE (153, 53)-(154, 66), 113, BF
LINE (155, 54)-(156, 67), 113, BF
LINE (157, 55)-(158, 68), 113, BF
LINE (159, 56)-(160, 69), 113, BF
LINE (161, 57)-(162, 70), 113, BF
LINE (163, 58)-(164, 71), 113, BF
LINE (165, 59)-(166, 72), 113, BF
LINE (167, 60)-(168, 73), 113, BF
LINE (169, 61)-(170, 74), 113, BF
LINE (171, 62)-(172, 75), 113, BF
LINE (173, 63)-(174, 76), 113, BF
LINE (175, 64)-(176, 77), 113, BF
LINE (177, 65)-(178, 78), 113, BF
LINE (179, 66)-(180, 79), 113, BF
LINE (181, 67)-(182, 80), 113, BF
LINE (183, 68)-(184, 81), 113, BF
LINE (185, 69)-(186, 82), 113, BF
LINE (187, 70)-(188, 83), 113, BF
LINE (189, 71)-(190, 84), 113, BF
LINE (191, 72)-(192, 85), 113, BF
LINE (193, 73)-(194, 86), 113, BF
LINE (195, 74)-(196, 87), 113, BF
LINE (197, 75)-(198, 88), 113, BF
LINE (199, 76)-(199, 89), 113
LINE (201, 76)-(209, 89), 111, BF
GOTO 29
28 LINE (214, 70)-(214, 35), 0
LINE (231, 76)-(231, 39), 0
LINE (214, 35)-(231, 39), 0
LINE (215, 36)-(217, 70), 0, BF
LINE (218, 37)-(220, 71), 0, BF
LINE (221, 38)-(223, 72), 0, BF
LINE (224, 39)-(227, 74), 0, BF
LINE (228, 40)-(230, 75), 0, BF
RETURN
29 IF TAULELL = 0 THEN GOSUB 1000
LOCATE 1, 1
PRINT A
LOCATE 1, 5
PRINT B
TAULELL = 0
A$ = INPUT$(1)
IF A = 134 AND B = 20 AND A$ = "6" THEN A = 130
IF A = 142 AND B = 24 AND A$ = "6" THEN A = 138
IF A = 150 AND B = 28 AND A$ = "6" THEN A = 146
IF A = 158 AND B = 32 AND A$ = "6" THEN A = 154
IF A = 166 AND B = 36 AND A$ = "6" THEN A = 162
IF A = 174 AND B = 40 AND A$ = "6" THEN A = 170
IF A = 202 AND B = 40 AND A$ = "4" THEN A = 206
IF A = 194 AND B = 36 AND A$ = "4" THEN A = 198
IF A = 194 AND B = 36 AND A$ = "2" THEN A = 202
IF A = 182 AND B = 32 AND A$ = "4" THEN A = 186
IF A = 182 AND B = 32 AND A$ = "2" THEN A = 194
IF A = 174 AND B = 28 AND A$ = "4" THEN A = 178
IF A = 174 AND B = 28 AND A$ = "2" THEN A = 182
IF A = 166 AND B = 24 AND A$ = "4" THEN A = 170
IF A = 166 AND B = 24 AND A$ = "2" THEN A = 174



IF A > 180 AND B = 44 AND A < 203 AND A$ = "8" THEN B = 48
IF A = 206 AND B = 28 AND A$ = "6" THEN 60
IF A = 198 AND B = 24 AND A$ = "6" THEN 60
IF A$ = "4" THEN A = A - 4
IF A$ = "6" THEN A = A + 4
IF A$ = "8" THEN B = B - 4
IF A$ = "2" THEN B = B + 4
IF A$ = "E" THEN END
IF B = 20 THEN B = 24
IF B = 64 THEN B = 60
GOTO 51
60 A = 50
B = 50
X = 300
Y = 95
61 LINE (1, 1)-(299, 109), 0, BF
LINE (1, 90)-(299, 90), 0
LINE (1, 1)-(299, 89), 22, BF
LINE (1, 91)-(299, 109), 24, BF
LINE (40, 90)-(75, 40), 0, BF
IF TRANSP = 0 THEN
LINE (101, 92)-(104, 95), 28
LINE (105, 95)-(107, 95), 23
LINE (104, 96)-(109, 96), 23
LINE (103, 97)-(111, 97), 23
LINE (104, 98)-(112, 98), 23
LINE (105, 99)-(111, 99), 23
LINE (106, 100)-(110, 100), 23
LINE (107, 101)-(109, 101), 23
PSET (108, 102), 23
LINE (103, 98)-(108, 103), 20
LINE (103, 99)-(107, 103), 20
LINE (108, 103)-(112, 99), 20
LINE (109, 103)-(112, 100), 20
END IF
IF YYYY = 300 THEN RETURN
GOSUB 1000
IF TRANSP = 10 THEN GOSUB 9000
COLOR 4
IF l = 100 THEN RETURN
LOCATE 15, 2
PRINT "                            "
IF TRANSP > 1 AND YYYY = 0 THEN GOSUB 65
LOCATE 15, 2
IF AGAFAR = 10 THEN PRINT "AGAFAR"
LOCATE 15, 2
IF A > 80 AND A < 105 AND AGAFAR = 10 THEN PRINT "AGAFAR TRANSPORTADOR"

IF HAB = 10 THEN LINE (1, 110)-(300, 170), 0, BF
IF HAB = 10 AND YYYY = 100 THEN GOSUB 67
LOCATE 15, 2
IF USAR = 10 AND TRANSP = 10 THEN PRINT "USAR TELETRANSPORTADOR"
A$ = INPUT$(1)
IF AGAFAR = 10 AND A$ = " " THEN TRANSP = 2
IF USAR = 10 AND TRANSP = 10 AND A$ = " " THEN 70
AGAFAR = 0
IF A$ = "E" THEN END
IF A$ = "6" THEN A = A + 4
IF A$ = "4" THEN A = A - 4
IF A$ = "8" THEN B = B - 4
IF A$ = "2" THEN B = B + 4
IF A$ = "A" THEN AGAFAR = 10
IF A$ = "U" THEN USAR = 10
GOTO 61
65 YYYY = 100
l = 100
PSET (X, Y), 4
PSET (X + 4, Y), 24
FOR T = 1 TO 800: NEXT T
X = X - 4
IF X < 120 THEN 66
GOTO 65
66 LOCATE 1, 2
PRINT "He noi aix• val 1.000 peles !"
FOR T = 1 TO 10000: NEXT T
HAB = 10
RETURN
67 YYYY = 200
LOCATE 17, 2
PRINT "1. Surt del mitg tro‡ de porc"
LOCATE 19, 2
PRINT "2. Si no m'ho dones et trpitjo NŠstor"
LOCATE 21, 2
PRINT "3. D'acord t'el compro per 1000$"
A$ = INPUT$(1)
GOSUB 5
LINE (1, 1)-(299, 50), 24, BF
GOSUB 61
l = 0
LOCATE 1, 2
IF A$ = "1" THEN
PRINT "Ves a la merda          "
TRANSP = 5
END IF
IF A$ = "2" THEN
PRINT "Et creus molt llest he ?"
TRANSP = 5
END IF
IF A$ = "3" THEN
PRINT "Tracte fet              "
BITLLET = 0
TRANSP = 10
GOSUB 9000
END IF
X = 120
FOR T = 1 TO 10000: NEXT T
LINE (1, 1)-(299, 20), 22, BF
68 PSET (X - 4, Y), 24
PSET (X, Y), 4
X = X + 4
FOR T = 1 TO 1000: NEXT T
IF X = 300 THEN 61
HAB = 0
GOTO 68
70
FOR T = 1 TO 5000: NEXT T
A = 140
B = -40
71
LINE (1, 1)-(299, 109), 9, BF
GOSUB 1000
LINE (120, 109)-(180, 90), 113, BF
LINE (100, 80)-(200, 90), 113, BF
LINE (100, 70)-(120, 80), 113, BF
LINE (140, 70)-(160, 80), 113, BF
LINE (180, 70)-(200, 80), 113, BF
LINE (280, 1)-(299, 109), 113, BF
IF H = 0 THEN B = B + 4
FOR T = 1 TO 500: NEXT T
IF B > 36 THEN H = 10
IF H = 0 THEN 71
A$ = INPUT$(1)
IF A$ = "4" THEN A = A - 4
IF A$ = "6" THEN A = A + 4
IF A$ = "E" THEN END
IF A < 100 THEN A = 100
IF A > 173 THEN A = 173
GOTO 71
END
END



END





1000 LINE (A + 8, B + 1)-(A + 10, B + 1), 185
LINE (A + 7, B + 2)-(A + 12, B + 4), 185, BF
LINE (A + 5, B + 4)-(A + 7, B + 4), 114
LINE (A + 4, B + 5)-(A + 5, B + 6), 114, BF
PSET (A + 5, B + 7), 114
PSET (A + 6, B + 8), 114
PSET (A + 6, B + 7), 185
LINE (A + 6, B + 5)-(A + 7, B + 6), 17, BF
LINE (A + 8, B + 5)-(A + 13, B + 5), 114
LINE (A + 12, B + 4)-(A + 13, B + 4), 186
LINE (A + 14, B + 5)-(A + 14, B + 7), 186
PSET (A + 15, B + 5), 186
LINE (A + 7, B + 6)-(A + 13, B + 7), 64, BF
PSET (A + 13, B + 6), 17
PSET (A + 11, B + 6), 17
LINE (A + 8, B + 8)-(A + 11, B + 9), 64, BF
PSET (A + 13, B + 8), 64
PSET (A + 12, B + 8), 64

LINE (A + 10, B + 6)-(A + 10, B + 8), 12
PSET (A + 9, B + 8), 12
PSET (A + 6, B + 7), 12
LINE (A + 7, B + 8)-(A + 7, B + 10), 12
LINE (A + 8, B + 10)-(A + 12, B + 12), 12, BF
LINE (A + 9, B + 11)-(A + 10, B + 11), 0
PSET (A + 8, B + 6), 17
PSET (A + 12, B + 9), 12
PSET (A + 7, B + 11), 90
LINE (A + 6, B + 12)-(A + 6, B + 13), 90
LINE (A + 7, B + 21)-(A + 7, B + 25), 114
LINE (A + 6, B + 14)-(A + 6, B + 25), 114
LINE (A + 5, B + 12)-(A + 5, B + 24), 114
LINE (A + 4, B + 13)-(A + 4, B + 24), 114
LINE (A + 4, B + 17)-(A + 4, B + 20), 185
LINE (A + 3, B + 13)-(A + 3, B + 20), 114
LINE (A + 2, B + 15)-(A + 2, B + 28), 114
LINE (A + 1, B + 19)-(A + 1, B + 28), 114
LINE (A + 3, B + 21)-(A + 3, B + 29), 185
PSET (A + 1, B + 29), 12
PSET (A + 1, B + 30), 64
PSET (A + 2, B + 29), 64
PSET (A + 2, B + 30), 12
PSET (A + 2, B + 31), 12
PSET (A + 3, B + 30), 12
PSET (A + 3, B + 31), 64
LINE (A + 4, B + 25)-(A + 5, B + 25), 185
LINE (A + 6, B + 26)-(A + 7, B + 26), 185
LINE (A + 7, B + 12)-(A + 7, B + 15), 64
LINE (A + 8, B + 13)-(A + 9, B + 17), 64, BF
LINE (A + 10, B + 14)-(A + 10, B + 16), 64
PSET (A + 11, B + 14), 64
LINE (A + 10, B + 13)-(A + 11, B + 13), 12, BF
LINE (A + 12, B + 13)-(A + 12, B + 14), 90
LINE (A + 13, B + 13)-(A + 13, B + 12), 90
LINE (A + 11, B + 15)-(A + 11, B + 17), 90
PSET (A + 10, B + 17), 90
LINE (A + 8, B + 18)-(A + 10, B + 24), 90, BF
LINE (A + 7, B + 16)-(A + 7, B + 20), 90
PSET (A + 9, B + 18), 186
LINE (A + 8, B + 21)-(A + 10, B + 19), 186
LINE (A + 11, B + 18)-(A + 11, B + 21), 186
LINE (A + 8, B + 25)-(A + 10, B + 25), 115
PSET (A + 10, B + 24), 115
LINE (A + 11, B + 22)-(A + 14, B + 25), 114, BF
LINE (A + 12, B + 15)-(A + 14, B + 21), 114, BF
LINE (A + 13, B + 14)-(A + 14, B + 14), 114
PSET (A + 14, B + 13), 114
LINE (A + 15, B + 14)-(A + 15, B + 17), 114
LINE (A + 15, B + 18)-(A + 15, B + 25), 186
PSET (A + 16, B + 14), 114
LINE (A + 16, B + 15)-(A + 18, B + 24), 114, BF
LINE (A + 17, B + 25)-(A + 17, B + 27), 114
PSET (A + 18, B + 25), 114
IF INDY = 10 THEN 11
GOTO 12
11 X = 100
GOTO 7
13
LINE (65, 49)-(89, 46), 113, BF
LINE (85, 50)-(60, 50), 0
LINE (85, 51)-(60, 65), 42, BF
GOTO 20
12 LINE (A + 19, B + 20)-(A + 19, B + 22), 114
LINE (A + 19, B + 23)-(A + 19, B + 25), 186
LINE (A + 18, B + 26)-(A + 19, B + 27), 186, BF
LINE (A + 17, B + 28)-(A + 19, B + 28), 64, BF
LINE (A + 17, B + 29)-(A + 18, B + 30), 12, BF
PSET (A + 18, B + 29), 64
PSET (A + 19, B + 29), 12
LINE (A + 6, B + 28)-(A + 6, B + 36), 114
LINE (A + 7, B + 28)-(A + 7, B + 29), 114
PSET (A + 8, B + 28), 114
LINE (A + 7, B + 30)-(A + 7, B + 33), 138
LINE (A + 7, B + 34)-(A + 8, B + 36), 138, BF
LINE (A + 9, B + 28)-(A + 10, B + 28), 138
PSET (A + 10, B + 29), 138
LINE (A + 11, B + 29)-(A + 11, B + 34), 138
LINE (A + 12, B + 35)-(A + 12, B + 38), 138
LINE (A + 9, B + 30)-(A + 10, B + 32), 185, BF
PSET (A + 9, B + 29), 185
LINE (A + 10, B + 32)-(A + 10, B + 36), 185
PSET (A + 11, B + 28), 114

LINE (A + 2, B + 47)-(A + 9, B + 47), 18
LINE (A + 4, B + 46)-(A + 7, B + 46), 18
LINE (A + 6, B + 43)-(A + 8, B + 45), 138, BF
PSET (A + 7, B + 44), 114
PSET (A + 6, B + 43), 114
LINE (A + 6, B + 37)-(A + 7, B + 42), 114, BF
LINE (A + 5, B + 27)-(A + 5, B + 36), 186
PSET (A + 6, B + 37), 186
LINE (A + 8, B + 37)-(A + 9, B + 42), 138, BF
PSET (A + 8, B + 42), 114
LINE (A + 9, B + 43)-(A + 10, B + 46), 186, BF
PSET (A + 8, B + 46), 186
LINE (A + 10, B + 46)-(A + 10, B + 40), 186
LINE (A + 9, B + 40)-(A + 9, B + 39), 186
LINE (A + 10, B + 37)-(A + 10, B + 38), 186
LINE (A + 9, B + 33)-(A + 9, B + 36), 186
LINE (A + 8, B + 29)-(A + 8, B + 33), 186
LINE (A + 12, B + 28)-(A + 13, B + 29), 114, BF
LINE (A + 12, B + 29)-(A + 12, B + 34), 114
LINE (A + 13, B + 33)-(A + 13, B + 38), 114
LINE (A + 14, B + 28)-(A + 14, B + 30), 138
LINE (A + 5, B + 27)-(A + 8, B + 27), 186
LINE (A + 8, B + 26)-(A + 10, B + 26), 186
LINE (A + 11, B + 26)-(A + 15, B + 26), 186
LINE (A + 13, B + 30)-(A + 13, B + 32), 138
LINE (A + 14, B + 33)-(A + 14, B + 34), 138
LINE (A + 15, B + 35)-(A + 15, B + 37), 138
LINE (A + 14, B + 35)-(A + 14, B + 37), 114
LINE (A + 11, B + 27)-(A + 15, B + 27), 186
LINE (A + 9, B + 27)-(A + 10, B + 27), 114
LINE (A + 15, B + 27)-(A + 15, B + 34), 186
LINE (A + 14, B + 31)-(A + 14, B + 32), 186
LINE (A + 16, B + 33)-(A + 16, B + 39), 186
PSET (A + 15, B + 38), 186
LINE (A + 13, B + 39)-(A + 15, B + 39), 138
PSET (A + 14, B + 38), 138
LINE (A + 13, B + 40)-(A + 16, B + 40), 114
LINE (A + 13, B + 41)-(A + 14, B + 41), 114
LINE (A + 14, B + 42)-(A + 15, B + 42), 114
LINE (A + 17, B + 38)-(A + 17, B + 44), 186
LINE (A + 16, B + 41)-(A + 16, B + 47), 186
LINE (A + 14, B + 42)-(A + 15, B + 47), 114, BF
LINE (A + 13, B + 43)-(A + 15, B + 43), 186
PSET (A + 13, B + 42), 186
PSET (A + 14, B + 44), 186
PSET (A + 15, B + 47), 186
PSET (A + 15, B + 41), 186
LINE (A + 14, B + 48)-(A + 17, B + 49), 18, BF
PSET (A + 18, B + 49), 18
LINE (A + 17, B + 45)-(A + 17, B + 47), 138
RETURN



9000 IF TRANSP = 10 THEN BITLLET = 0
IF MAPA = 0 THEN GOSUB 9002
IF MAPA = 20 THEN GOSUB 9001
IF MAPA = 20 AND TRANSP = 10 THEN
C = 212
D = 135
END IF
IF MAPA = 0 AND TRANSP = 10 THEN
C = 186
D = 135
IF TRANSP = 10 THEN GOSUB 90002
END IF
RETURN
90002 LINE (C + 1, D + 1)-(C + 4, D + 4), 28
LINE (C + 5, D + 4)-(C + 7, D + 4), 23
LINE (C + 4, D + 5)-(C + 9, D + 5), 23
LINE (C + 3, D + 6)-(C + 11, D + 6), 23
LINE (C + 4, D + 7)-(C + 12, D + 7), 23
LINE (C + 5, D + 8)-(C + 11, D + 8), 23
LINE (C + 6, D + 9)-(C + 10, D + 9), 23
LINE (C + 7, D + 10)-(C + 9, D + 10), 23
PSET (C + 8, D + 11), 23
PSET (C + 6, D + 5), 4
PSET (C + 5, D + 6), 4
LINE (C + 6, D + 6)-(C + 7, D + 7), 4, BF
LINE (C + 3, D + 7)-(C + 8, D + 12), 20
LINE (C + 3, D + 8)-(C + 7, D + 12), 20
LINE (C + 8, D + 12)-(C + 12, D + 8), 20
LINE (C + 9, D + 12)-(C + 12, D + 9), 20
RETURN
9002 IF BITLLET > 0 THEN
LINE (186, 135)-(201, 143), 10, BF
LINE (186, 143)-(201, 143), 2
LINE (201, 143)-(201, 135), 2
END IF
RETURN
9001 IF BITLLET > 0 THEN
LINE (212, 133)-(227, 142), 2, BF
LINE (212, 133)-(227, 133), 10
LINE (227, 133)-(227, 142), 10
END IF
RETURN


10001 LOCATE 5, 1
LINE (0, 0)-(300, 170), 0, BF
PRINT "  ___         __"
PRINT " |    |\   | |  \"
PRINT " |__  | \  | |  |"
PRINT " |    |  \ | |  |"
PRINT " |___ |   \| |__/"







END
33

SUB joe
SCREEN 13
100 X = X + 1
VIEW (0, 0)-(300, 170), 0
LINE (0, 0)-(300, 170), X, BF
A$ = INPUT$(1)
IF A$ = "w" THEN END
GOTO 100
END SUB

