5 CLS
COLOR 15
PRINT ""
PRINT "                                  OOOOOOOOOOOOOO"
PRINT "                                OOOOOOOOOOOOOOOOOO"
PRINT ""
COLOR 10
PRINT ""
PRINT ""
PRINT "       OOOOOOOO                               OOOOOOO"
PRINT "      OOOOOOOOOOO                           OOOOOOOOOOO"
PRINT "     OOOOOOOOOOOOO                         OOOOOOOOOOOOO"
PRINT "      OOOOOOOOOO                             OOOOOOOOOO"
PRINT "       OOOOOOOO                               OOOOOOOO"
COLOR 6
PRINT "  1       OO             2                       OO          3 "
PRINT "          OO                                     OO"
PRINT "          OO                                     OO"
PRINT "          OO                                     OO"
PRINT "          OO                                     OO"
PRINT "          OO                                     OO"
COLOR 2
FOR T = 1 TO 5
PRINT "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO"
NEXT T
A$ = INPUT$(1)
IF A$ = "1" THEN 10
IF A$ = "2" THEN 10
IF A$ = "3" THEN 10
GOTO 5
10 CLS
COLOR 4
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "      OOOOOOOOO   O     O  OOOOOO    O   O   OOOOOO  O      O  OOOOOOO  "
PRINT "          O       O O   O  O     O    O O    O    O  O O    O  O     O"
PRINT "          O       O  O  O  O     O     O     OOOOOO  O   O  O  OOOOOOO"
COLOR 14
PRINT "          O       O   O O  O     O     O     O    O  O     OO  O     O"
PRINT "      OOOOOOOOO   O     O  OOOOOO      O     O    O  O      O  O     O"
PRINT ""
PRINT ""
COLOR 4
PRINT " "
PRINT "               OOOOOOO    OOOOOO   O      O  OOOOOO   OOOOOO"
PRINT "                     O   O      O  O  O   O  O        O"
PRINT "                     O   O      O  O   O  O  OOOO     OOOOOO"
COLOR 14
PRINT "               O     O   O      O  O    O O  O             O"
PRINT "                OOOOO     OOOOOO   O      O  OOOOOO   OOOOOO"


END

