










look = 1
CLS
LOCATE 10, 5
PRINT "1.START"
LOCATE 12, 5
PRINT "2.NEW GAME"
LOCATE 14, 5
DO
LOOP UNTIL INKEY$ = CHR$(27)
A$ = INPUT$(1)



SCREEN 13
VIEW (0, 0)-(300, 170), 0
IF A$ = "1" THEN 4
3 LINE (0, 0)-(300, 170), 0
LINE (10, 150)-(50, 70), 6
LINE (50, 70)-(60, 70), 6
LINE (60, 70)-(55, 80), 6
LINE (55, 80)-(65, 80), 6
LINE (65, 80)-(70, 70), 6
LINE (70, 70)-(80, 70), 6
LINE (80, 70)-(75, 80), 6
LINE (75, 80)-(85, 80), 6
LINE (85, 80)-(90, 70), 6
LINE (90, 70)-(100, 70), 6
LINE (100, 70)-(90, 100), 6
LINE (90, 100)-(100, 100), 6
LINE (100, 100)-(105, 90), 6
LINE (105, 90)-(115, 90), 6
LINE (115, 90)-(112, 100), 6
LINE (112, 100)-(120, 100), 6
LINE (120, 100)-(122, 90), 6
LINE (122, 90)-(128, 90), 6
LINE (128, 90)-(130, 100), 6
LINE (130, 100)-(140, 100), 6
LINE (140, 100)-(137, 90), 6
LINE (137, 90)-(145, 90), 6
LINE (145, 90)-(150, 100), 6
LINE (150, 100)-(160, 100), 6
LINE (160, 100)-(150, 70), 6
LINE (150, 70)-(160, 70), 6
LINE (160, 70)-(165, 80), 6
LINE (165, 80)-(175, 80), 6
LINE (175, 80)-(170, 70), 6
LINE (170, 70)-(180, 70), 6
LINE (180, 70)-(185, 80), 6
LINE (185, 80)-(195, 80), 6
LINE (195, 80)-(190, 70), 6
LINE (190, 70)-(200, 70), 6
LINE (200, 70)-(240, 150), 6
LINE (10, 150)-(240, 150), 6
LINE (100, 150)-(115, 120), 6
LINE (115, 120)-(140, 120), 6
LINE (140, 120)-(155, 150), 6
PAINT (100, 120), 114, 6
PAINT (140, 140), 186, 6
LINE (5, 151)-(250, 151), 2
LINE (3, 152)-(254, 152), 2
LINE (1, 153)-(258, 153), 2
LINE (0, 154)-(262, 154), 2
LINE (0, 155)-(266, 155), 2
LINE (0, 156)-(270, 156), 2
LINE (0, 157)-(274, 157), 2
LINE (0, 158)-(278, 158), 2
LINE (0, 159)-(282, 159), 2
LINE (0, 160)-(286, 160), 2
LINE (0, 161)-(290, 161), 2
LINE (0, 162)-(294, 162), 2
LINE (0, 163)-(298, 163), 2
LINE (0, 164)-(300, 164), 2, BF
FOR t = 16 TO 29
COLOR t
LOCATE 4, 10
PRINT "Una negra noche..."
FOR e = 1 TO 1000: NEXT e
NEXT t
FOR e = 1 TO 1000: NEXT e
FOR t = 29 TO 16 STEP -1
COLOR t
LOCATE 4, 10
PRINT "Una negra noche..."
FOR e = 1 TO 1000: NEXT e
NEXT t
FOR e = 1 TO 2000: NEXT e

FOR t = 16 TO 29
COLOR t
LOCATE 4, 10
PRINT "en un castillo..."
FOR e = 1 TO 1000: NEXT e
NEXT t
FOR e = 1 TO 1000: NEXT e
FOR t = 29 TO 16 STEP -1
COLOR t
LOCATE 4, 10
PRINT "en un castillo..."
FOR e = 1 TO 1000: NEXT e
NEXT t
FOR e = 1 TO 19000: NEXT e
LOCATE 6, 2
COLOR 4
PRINT "Donde esta mi cena"
FOR e = 1 TO 25000: NEXT e
LOCATE 6, 2
PRINT "                        "
LOCATE 2, 15
COLOR 2
PRINT "Ahora va se¤or"
FOR e = 1 TO 20000: NEXT e
LOCATE 2, 15
PRINT "              "
LOCATE 6, 2
COLOR 4
PRINT "Muy bien"
FOR e = 1 TO 30000: NEXT e
LOCATE 6, 2
PRINT "         "
LOCATE 2, 15
COLOR 2
PRINT "Le ha gustado se¤or"
FOR e = 1 TO 20000: NEXT e
LOCATE 2, 15
PRINT "                   "
LOCATE 6, 2
COLOR 4
PRINT "Phuphaaaa... que asco"
FOR e = 1 TO 20000: NEXT e
LOCATE 6, 2
PRINT "                     "
LOCATE 6, 2
PRINT "Toma eso..."
FOR e = 1 TO 20000: NEXT e
LOCATE 2, 15
COLOR 2
PRINT "No, no por fabor..."
FOR t = 1 TO 20000: NEXT t
LOCATE 6, 2
COLOR 4
PRINT "Pam Pam Pam"
FOR e = 1 TO 40000: NEXT e
LOCATE 2, 15
PRINT "                  "
LOCATE 6, 2
PRINT "           "
LOCATE 4, 20
COLOR 5
PRINT "Mirad, que ha pasado?"
FOR e = 1 TO 15000: NEXT e
LOCATE 4, 20
PRINT "                     "
LOCATE 7, 13
COLOR 3
PRINT "D¢nde esta el Rey "
FOR e = 1 TO 15000: NEXT e
LOCATE 7, 13
PRINT "                  "
FOR e = 1 TO 25000: NEXT e
4 LINE (0, 0)-(300, 170), 0, BF





















A = 100
B = 5
x = 7
xx = 7
xxX = 7
xxxx = 7
xxxxx = 7
xxxxxx = 7
xxxxxxx = 7
xxxxxxxx = 7
xxxxxxxxx = 7
VIEW (0, 0)-(300, 170), 22
5

LINE (3, 132)-(3, 138), 14
LINE (3, 132)-(6, 132), 14
LINE (7, 133)-(7, 137), 14
LINE (3, 138)-(6, 138), 14
LINE (9, 135)-(9, 137), x
LINE (10, 134)-(11, 134), x
LINE (12, 135)-(12, 137), x
LINE (10, 138)-(11, 138), x
LINE (14, 134)-(14, 138), x
PSET (15, 135), x
PSET (16, 134), x
LINE (17, 135)-(17, 138), x
PSET (19, 137), x
LINE (20, 134)-(21, 134), x
LINE (20, 136)-(21, 136), x
LINE (20, 138)-(21, 138), x
LINE (22, 135)-(22, 137), x
PSET (23, 138), x
LINE (25, 134)-(25, 138), x
PSET (26, 135), x
LINE (27, 134)-(28, 134), x

LINE (3, 147)-(3, 151), 14
LINE (4, 146)-(6, 146), 14
LINE (7, 147)-(7, 151), 14
LINE (4, 152)-(6, 152), 14
LINE (9, 146)-(9, 152), xx
LINE (10, 148)-(11, 148), xx
LINE (12, 149)-(12, 151), xx
PSET (11, 152), xx
PSET (10, 151), xx
LINE (14, 148)-(14, 152), xx
PSET (15, 149), xx
LINE (16, 148)-(17, 148), xx
LINE (19, 148)-(20, 148), xx
LINE (20, 148)-(20, 152), xx
LINE (19, 152)-(21, 152), xx
PSET (20, 146), xx
LINE (23, 148)-(23, 152), xx
PSET (24, 149), xx
LINE (25, 148)-(26, 148), xx

LINE (3, 165)-(3, 159), xxX
LINE (3, 159)-(6, 162), xxX
LINE (6, 162)-(9, 159), xxX
LINE (9, 159)-(9, 165), xxX
LINE (11, 165)-(13, 165), 14
LINE (12, 161)-(12, 165), 14
PSET (11, 161), 14
PSET (12, 159), 14
LINE (15, 161)-(15, 165), xxX
PSET (16, 162), xxX
LINE (17, 161)-(18, 161), xxX
PSET (20, 164), xxX
LINE (21, 161)-(22, 161), xxX
LINE (21, 163)-(22, 163), xxX
LINE (21, 165)-(22, 165), xxX
LINE (23, 162)-(23, 164), xxX
PSET (24, 165), xxX
LINE (26, 161)-(26, 165), xxX
PSET (27, 162), xxX
LINE (28, 161)-(29, 161), xxX

LINE (40, 132)-(40, 138), xxxx
LINE (40, 132)-(43, 132), xxxx
LINE (40, 135)-(42, 135), xxxx
LINE (40, 138)-(43, 138), xxxx
LINE (45, 134)-(45, 138), 14
PSET (46, 135), 14
PSET (47, 134), 14
LINE (48, 135)-(48, 138), 14
LINE (50, 134)-(50, 138), xxxx
PSET (51, 135), xxxx
LINE (52, 134)-(53, 134), xxxx
PSET (54, 137), xxxx
LINE (55, 134)-(56, 134), xxxx
LINE (55, 136)-(56, 136), xxxx
LINE (55, 138)-(56, 138), xxxx
LINE (57, 135)-(57, 137), xxxx
PSET (58, 138), xxxx
LINE (60, 135)-(60, 137), xxxx
LINE (61, 134)-(62, 134), xxxx
LINE (61, 138)-(62, 138), xxxx
LINE (63, 135)-(63, 137), xxxx
LINE (65, 134)-(65, 138), xxxx
PSET (66, 135), xxxx
PSET (67, 134), xxxx
LINE (68, 135)-(68, 138), xxxx
PSET (70, 137), xxxx
LINE (71, 134)-(72, 134), xxxx
LINE (71, 136)-(72, 136), xxxx
LINE (71, 138)-(72, 138), xxxx
LINE (73, 135)-(73, 137), xxxx
PSET (74, 138), xxxx
LINE (76, 134)-(76, 138), xxxx
PSET (77, 135), xxxx
LINE (78, 134)-(79, 134), xxxx
 
LINE (42, 146)-(42, 152), 14
LINE (40, 146)-(44, 146), 14
PSET (45, 151), xxxxx
LINE (46, 148)-(47, 148), xxxxx
LINE (46, 150)-(47, 150), xxxxx
LINE (46, 152)-(47, 152), xxxxx
LINE (48, 149)-(48, 151), xxxxx
PSET (49, 152), xxxxx
LINE (51, 148)-(51, 152), xxxxx
PSET (52, 149), xxxxx
PSET (53, 148), xxxxx
LINE (54, 149)-(54, 152), xxxxx
LINE (56, 149)-(56, 151), xxxxx
LINE (57, 148)-(58, 148), xxxxx
LINE (57, 152)-(58, 152), xxxxx
PSET (60, 151), xxxxx
LINE (61, 148)-(62, 148), xxxxx
LINE (61, 150)-(62, 150), xxxxx
LINE (61, 152)-(62, 152), xxxxx
LINE (63, 149)-(63, 151), xxxxx
PSET (64, 152), xxxxx
LINE (66, 148)-(66, 152), xxxxx
PSET (67, 149), xxxxx
LINE (68, 148)-(69, 148), xxxxx

LINE (40, 159)-(43, 159), 14
LINE (40, 159)-(40, 165), 14
LINE (40, 162)-(42, 162), 14
LINE (40, 165)-(42, 165), 14
LINE (45, 161)-(45, 165), xxxxxx
PSET (46, 161), xxxxxx
LINE (47, 162)-(47, 165), xxxxxx
LINE (48, 161)-(49, 161), xxxxxx
LINE (50, 162)-(50, 165), xxxxxx
LINE (52, 166)-(52, 161), xxxxxx
PSET (53, 163), xxxxxx
PSET (54, 164), xxxxxx
LINE (52, 161)-(54, 161), xxxxxx
LINE (55, 162)-(55, 163), xxxxxx
LINE (57, 161)-(57, 164), xxxxxx
LINE (60, 161)-(60, 165), xxxxxx
PSET (58, 165), xxxxxx
PSET (59, 164), xxxxxx
LINE (63, 159)-(63, 165), xxxxxx
LINE (62, 160)-(64, 160), xxxxxx
LINE (66, 161)-(70, 165), xxxxxx
LINE (66, 165)-(70, 161), xxxxxx
PSET (72, 164), xxxxxx
LINE (73, 161)-(74, 161), xxxxxx
LINE (73, 163)-(74, 163), xxxxxx
LINE (73, 165)-(74, 165), xxxxxx
LINE (75, 162)-(75, 164), xxxxxx
PSET (76, 165), xxxxxx
LINE (78, 161)-(78, 165), xxxxxx
PSET (79, 162), xxxxxx
LINE (80, 161)-(81, 161), xxxxxx
LINE (91, 132)-(91, 137), 14
LINE (92, 138)-(94, 138), 14
LINE (95, 132)-(95, 137), 14
LINE (97, 138)-(99, 138), xxxxxxx
PSET (100, 137), xxxxxxx
LINE (98, 136)-(99, 136), xxxxxxx
PSET (97, 135), xxxxxxx
LINE (98, 134)-(100, 134), xxxxxxx
PSET (102, 137), xxxxxxx
LINE (103, 138)-(104, 138), xxxxxxx
LINE (103, 136)-(104, 136), xxxxxxx
LINE (103, 134)-(104, 134), xxxxxxx
LINE (105, 135)-(105, 137), xxxxxxx
PSET (106, 138), xxxxxxx
LINE (108, 134)-(108, 138), xxxxxxx
PSET (109, 135), xxxxxxx
LINE (110, 134)-(111, 134), xxxxxxx

LINE (91, 146)-(91, 152), 14
LINE (92, 146)-(95, 146), 14
LINE (95, 146)-(95, 152), 14
LINE (91, 149)-(95, 149), 14
LINE (97, 153)-(99, 153), xxxxxxxx
LINE (100, 149)-(100, 152), xxxxxxxx
PSET (98, 151), xxxxxxxx
PSET (99, 150), xxxxxxxx
LINE (97, 149)-(97, 150), xxxxxxxx
LINE (98, 148)-(99, 148), xxxxxxxx
PSET (102, 151), xxxxxxxx
LINE (103, 148)-(104, 148), xxxxxxxx
LINE (103, 150)-(104, 150), xxxxxxxx
LINE (103, 152)-(104, 152), xxxxxxxx
LINE (105, 149)-(105, 151), xxxxxxxx
PSET (106, 152), xxxxxxxx
LINE (108, 149)-(108, 152), xxxxxxxx
LINE (109, 148)-(110, 148), xxxxxxxx
PSET (109, 150), xxxxxxxx
PSET (112, 151), xxxxxxxx
LINE (113, 148)-(114, 148), xxxxxxxx
LINE (113, 150)-(114, 150), xxxxxxxx
LINE (113, 152)-(114, 152), xxxxxxxx
LINE (115, 149)-(115, 151), xxxxxxxx
PSET (116, 152), xxxxxxxx
LINE (118, 148)-(118, 152), xxxxxxxx
PSET (119, 149), xxxxxxxx
LINE (120, 148)-(121, 148), xxxxxxxx

LINE (90, 159)-(90, 165), 14
LINE (90, 159)-(93, 162), 14
LINE (93, 162)-(96, 159), 14
LINE (96, 159)-(96, 165), 14
PSET (98, 164), xxxxxxxxx
LINE (99, 161)-(100, 161), xxxxxxxxx
LINE (99, 163)-(100, 163), xxxxxxxxx
LINE (99, 165)-(100, 165), xxxxxxxxx
LINE (101, 162)-(101, 164), xxxxxxxxx
PSET (102, 165), xxxxxxxxx
LINE (104, 159)-(104, 165), xxxxxxxxx
LINE (103, 160)-(105, 160), xxxxxxxxx
PSET (106, 164), xxxxxxxxx
LINE (107, 161)-(108, 161), xxxxxxxxx
LINE (107, 163)-(108, 163), xxxxxxxxx
LINE (107, 165)-(108, 165), xxxxxxxxx
LINE (109, 162)-(109, 164), xxxxxxxxx
PSET (110, 165), xxxxxxxxx
LINE (112, 161)-(112, 165), xxxxxxxxx
PSET (113, 162), xxxxxxxxx
LINE (114, 161)-(115, 161), xxxxxxxxx
x = 7
xx = 7
xxX = 7
xxxx = 7
xxxxx = 7
xxxxxx = 7
xxxxxxx = 7
xxxxxxxx = 7
xxxxxxxxx = 7




I = 23
2 LINE (161, 136)-(166, 131), I
LINE (166, 131)-(171, 136), I
LINE (161, 136)-(164, 136), I
LINE (171, 136)-(168, 136), I
LINE (164, 136)-(164, 145), I
LINE (168, 136)-(168, 145), I
LINE (164, 145)-(168, 145), I
LINE (164, 151)-(168, 151), I
LINE (164, 151)-(164, 160), I
LINE (168, 151)-(168, 160), I
LINE (164, 160)-(161, 160), I
LINE (161, 160)-(166, 165), I
LINE (168, 160)-(171, 160), I
LINE (171, 160)-(166, 165), I

sen = 24
LINE (1, 167)-(129, 167), sen
LINE (1, 141)-(129, 155), sen, B
LINE (34, 131)-(34, 167), sen
LINE (84, 131)-(84, 167), sen
LINE (129, 131)-(129, 167), sen
LINE (1, 131)-(1, 167), 22
PSET (1, 141), sen
PSET (1, 155), sen
PSET (1, 167), sen
LINE (0, 130)-(130, 168), 0, B
LINE (0, 142)-(130, 156), 0, B
LINE (35, 130)-(85, 168), 0, B
LINE (180, 130)-(292, 168), 0, B
LINE (181, 148)-(291, 148), sen
LINE (181, 167)-(291, 167), sen
LINE (181 + 26, 131)-(181 + 26, 167), sen
LINE (181 + 28 + 26, 131)-(181 + 26 + 28, 167), sen
LINE (181 + 28 + 28 + 26, 131)-(181 + 27 + 27 + 28, 167), sen
LINE (181 + (28 * 3) + 26, 131)-(181 + (28 * 3) + 26, 167), sen
LINE (180, 149)-(292, 149), 0
LINE (208, 130)-(208 + 28, 168), 0, B
LINE (208 + 84, 130)-(208 + 56, 168), 0, B
A = 200
B = 45

LINE (0, 0)-(300, 110), 0, BF
LINE (0, 110)-(300, 125), 25, BF
LINE (1, 111)-(299, 124), 0, BF
LINE (1, 126)-(300, 126), sen
LINE (1, 124)-(300, 124), sen
LINE (154, 126)-(154, 169), sen
LINE (176, 126)-(176, 169), sen
LINE (0, 125)-(300, 170), 0, B
LINE (177, 125)-(155, 170), 0, B
LINE (0, 0)-(300, 109), 19, B
1
LINE (1, 90)-(40, 60), 15
LINE (40, 60)-(250, -1), 15, B








GOSUB 10

A$ = INPUT$(1)
LINE (A - 18, B)-(A + 18, B + 42), 0, BF
IF A$ = "6" AND look = 3 THEN
    look = 1
    A = A + 10
    GOTO 1
END IF
IF A$ = "6" AND look = 1 THEN
    look = 3
    A = A + 4
    GOTO 1
END IF
IF A$ = "4" AND look = 2 THEN
    look = 4
    A = A - 4
    GOTO 1
END IF
IF A$ = "4" AND look = 4 THEN
    look = 2
    A = A - 10
    GOTO 1
END IF
IF A$ = "4" AND look = 1 THEN look = 2
IF A$ = "4" AND look = 3 THEN look = 4
IF A$ = "6" AND look = 2 THEN look = 1
IF A$ = "6" AND look = 4 THEN look = 3
IF A$ = "E" THEN END
GOTO 1
10 IF look = 1 THEN
LINE (A + 1, B + 2)-(A + 6, B + 8), 64, BF
LINE (A + 2, B + 1)-(A + 6, B + 1), 14
LINE (A + 1, B + 2)-(A + 4, B + 2), 14
LINE (A + 1, B + 3)-(A + 3, B + 3), 14
LINE (A + 1, B + 4)-(A + 2, B + 5), 14, BF
PSET (A + 6, B + 3), 15
PSET (A + 7, B + 4), 64
PSET (A + 7, B + 5), 64
PSET (A + 8, B + 5), 64
LINE (A + 5, B + 7)-(A + 6, B + 7), 0
LINE (A + 2, B + 9)-(A + 5, B + 11), 64, BF
LINE (A + 1, B + 11)-(A + 3, B + 11), 7
LINE (A + 1, B + 12)-(A + 5, B + 12), 7
LINE (A + 1, B + 13)-(A + 6, B + 24), 7, BF
LINE (A + 4, B + 25)-(A + 6, B + 25), 6
PSET (A + 1, B + 25), 6
LINE (A + 1, B + 26)-(A + 4, B + 37), 1, BF
LINE (A + 1, B + 38)-(A + 3, B + 39), 64, BF
LINE (A + 1, B + 40)-(A + 4, B + 42), 114, BF
LINE (A + 5, B + 41)-(A + 5, B + 42), 114
LINE (A + 5, B + 26)-(A + 6, B + 36), 9, BF
LINE (A + 5, B + 37)-(A + 6, B + 38), 64, BF
LINE (A + 5, B + 39)-(A + 6, B + 40), 6, BF
LINE (A + 6, B + 40)-(A + 8, B + 41), 6, BF
LINE (A + 3, B + 13)-(A + 4, B + 13), 8
LINE (A + 2, B + 14)-(A + 4, B + 17), 8, BF
LINE (A + 2, B + 18)-(A + 3, B + 28), 64, BF
LINE (A + 4, B + 26)-(A + 4, B + 28), 64
END IF
IF look = 2 THEN

LINE (A - 1, B + 2)-(A + -6, B + 8), 64, BF
LINE (A - 2, B + 1)-(A + -6, B + 1), 14
LINE (A - 1, B + 2)-(A + -4, B + 2), 14
LINE (A - 1, B + 3)-(A + -3, B + 3), 14
LINE (A - 1, B + 4)-(A + -2, B + 5), 14, BF
PSET (A - 6, B + 3), 15
PSET (A - 7, B + 4), 64
PSET (A - 7, B + 5), 64
PSET (A - 8, B + 5), 64
LINE (A - 5, B + 7)-(A + -6, B + 7), 0
LINE (A - 2, B + 9)-(A + -5, B + 11), 64, BF
LINE (A - 1, B + 11)-(A + -3, B + 11), 7
LINE (A - 1, B + 12)-(A + -5, B + 12), 7
LINE (A - 1, B + 13)-(A + -6, B + 24), 7, BF
LINE (A - 4, B + 25)-(A + -6, B + 25), 6
PSET (A - 1, B + 25), 6
LINE (A - 1, B + 26)-(A + -4, B + 37), 1, BF
LINE (A - 1, B + 38)-(A + -3, B + 39), 64, BF
LINE (A - 1, B + 40)-(A + -4, B + 42), 114, BF
LINE (A - 5, B + 41)-(A + -5, B + 42), 114
LINE (A - 5, B + 26)-(A + -6, B + 36), 9, BF
LINE (A - 5, B + 37)-(A + -6, B + 38), 64, BF
LINE (A - 5, B + 39)-(A + -6, B + 40), 6, BF
LINE (A - 6, B + 40)-(A + -8, B + 41), 6, BF
LINE (A - 3, B + 13)-(A + -4, B + 13), 8
LINE (A - 2, B + 14)-(A + -4, B + 17), 8, BF
LINE (A - 2, B + 18)-(A + -3, B + 28), 64, BF
LINE (A - 4, B + 26)-(A + -4, B + 28), 64
END IF
IF look = 3 THEN

LINE (A + 4, B + 2)-(A + 9, B + 8), 64, BF
LINE (A + 5, B + 1)-(A + 9, B + 1), 14
LINE (A + 4, B + 2)-(A + 7, B + 2), 14
LINE (A + 4, B + 3)-(A + 6, B + 3), 14
LINE (A + 4, B + 4)-(A + 5, B + 5), 14, BF
PSET (A + 9, B + 3), 15
PSET (A + 10, B + 4), 64
PSET (A + 10, B + 5), 64
PSET (A + 11, B + 5), 64
LINE (A + 8, B + 7)-(A + 9, B + 7), 0
LINE (A + 5, B + 9)-(A + 8, B + 11), 64, BF
LINE (A + 4, B + 11)-(A + 6, B + 11), 7
LINE (A + 4, B + 12)-(A + 8, B + 12), 7
LINE (A + 4, B + 13)-(A + 9, B + 24), 7, BF
LINE (A + 6, B + 13)-(A + 7, B + 13), 8
LINE (A + 5, B + 14)-(A + 7, B + 17), 8, BF
LINE (A + 5, B + 18)-(A + 6, B + 20), 64, BF
LINE (A + 7, B + 19)-(A + 13, B + 20), 64, BF
LINE (A + 12, B + 18)-(A + 13, B + 18), 64
LINE (A + 1, B + 15)-(A + 1, B + 18), 64
LINE (A + 2, B + 14)-(A + 2, B + 19), 64
LINE (A + 3, B + 13)-(A + 3, B + 15), 64
LINE (A + 3, B + 18)-(A + 3, B + 20), 64
LINE (A + 4, B + 25)-(A + 9, B + 25), 6
LINE (A + 5, B + 26)-(A + 9, B + 35), 9, BF
LINE (A + 4, B + 34)-(A + 7, B + 35), 9, BF
LINE (A + 3, B + 36)-(A + 5, B + 40), 9, BF
LINE (A + 2, B + 38)-(A + 2, B + 39), 9
LINE (A + 2, B + 40)-(A + 3, B + 41), 6, BF
LINE (A + 4, B + 41)-(A + 5, B + 42), 6, BF
PSET (A + 6, B + 42), 6
PSET (A + 6, B + 36), 9
LINE (A + 4, B + 26)-(A + 7, B + 29), 1, BF
LINE (A + 5, B + 29)-(A + 8, B + 30), 1, BF
PSET (A + 6, B + 31), 1
LINE (A + 7, B + 31)-(A + 9, B + 34), 1, BF
LINE (A + 8, B + 33)-(A + 10, B + 37), 1, BF
LINE (A + 9, B + 38)-(A + 12, B + 40), 1, BF
LINE (A + 9, B + 41)-(A + 10, B + 41), 1
LINE (A + 11, B + 41)-(A + 12, B + 41), 114
LINE (A + 9, B + 42)-(A + 14, B + 42), 114
END IF
IF look = 4 THEN

LINE (A - 4, B + 2)-(A - 9, B + 8), 64, BF
LINE (A - 5, B + 1)-(A - 9, B + 1), 14
LINE (A - 4, B + 2)-(A - 7, B + 2), 14
LINE (A - 4, B + 3)-(A - 6, B + 3), 14
LINE (A - 4, B + 4)-(A - 5, B + 5), 14, BF
PSET (A - 9, B + 3), 15
PSET (A - 10, B + 4), 64
PSET (A - 10, B + 5), 64
PSET (A - 11, B + 5), 64
LINE (A - 8, B + 7)-(A - 9, B + 7), 0
LINE (A - 5, B + 9)-(A - 8, B + 11), 64, BF
LINE (A - 4, B + 11)-(A - 6, B + 11), 7
LINE (A - 4, B + 12)-(A - 8, B + 12), 7
LINE (A - 4, B + 13)-(A - 9, B + 24), 7, BF
LINE (A - 6, B + 13)-(A - 7, B + 13), 8
LINE (A - 5, B + 14)-(A - 7, B + 17), 8, BF
LINE (A - 5, B + 18)-(A - 6, B + 20), 64, BF
LINE (A - 7, B + 19)-(A - 13, B + 20), 64, BF
LINE (A - 12, B + 18)-(A - 13, B + 18), 64
LINE (A - 1, B + 15)-(A - 1, B + 18), 64
LINE (A - 2, B + 14)-(A - 2, B + 19), 64
LINE (A - 3, B + 13)-(A - 3, B + 15), 64
LINE (A - 3, B + 18)-(A - 3, B + 20), 64
LINE (A - 4, B + 25)-(A - 9, B + 25), 6
LINE (A - 5, B + 26)-(A - 9, B + 35), 9, BF
LINE (A - 4, B + 34)-(A - 7, B + 35), 9, BF
LINE (A - 3, B + 36)-(A - 5, B + 40), 9, BF
LINE (A - 2, B + 38)-(A - 2, B + 39), 9
LINE (A - 2, B + 40)-(A - 3, B + 41), 6, BF
LINE (A - 4, B + 41)-(A - 5, B + 42), 6, BF
PSET (A - 6, B + 42), 6
PSET (A - 6, B + 36), 9
LINE (A - 4, B + 26)-(A - 7, B + 29), 1, BF
LINE (A - 5, B + 29)-(A - 8, B + 30), 1, BF
PSET (A - 6, B + 31), 1
LINE (A - 7, B + 31)-(A - 9, B + 34), 1, BF
LINE (A - 8, B + 33)-(A - 10, B + 37), 1, BF
LINE (A - 9, B + 38)-(A - 12, B + 40), 1, BF
LINE (A - 9, B + 41)-(A - 10, B + 41), 1
LINE (A - 11, B + 41)-(A - 12, B + 41), 114
LINE (A - 9, B + 42)-(A - 14, B + 42), 114
END IF
RETURN

END

SUB joe
SCREEN 13
100 x = x + 1
VIEW (0, 0)-(300, 170), 0
LINE (0, 0)-(300, 170), x, BF
A$ = INPUT$(1)
IF A$ = "w" THEN END
GOTO 100
END SUB

