CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
COLOR 14
PRINT "   _____         ____   _____  _____          _____"
PRINT "     |   |\   |  |   \    |    |   |  |\   |  |   |"
PRINT "     |   | \  |  |   |    |    |___|  | \  |  |___|"
COLOR 12
PRINT "     |   |  \ |  |   |    |    |   |  |  \ |  |   |"
COLOR 4
PRINT "   __|__ |   \|  |___/  __|__  |   |  |   \|  |   |"
PRINT ""
PRINT ""
COLOR 14
PRINT ""
PRINT "               _____  _____         _____  _____"
PRINT "                   |  |   |  |\   | |      | "
PRINT "                   |  |   |  | \  | |__    |____"
COLOR 12
PRINT "                   |  |   |  |  \ | |          |"
COLOR 4
PRINT "               |___|  |___|  |   \| |____  ____|"
PRINT ""
PRINT ""
PRINT "             I N   A   D O O M    S E C R E T"

A$ = INPUT$(1)
CLS
PRINT ""
PRINT ""
COLOR 15
PRINT "    __________________________________________________________________"
PRINT "    |                                                                |"
PRINT "    |                           M A P A                              |"
PRINT "    |                                                                |"
PRINT "    |  X - - - - -                                   /^\             |"
PRINT "    |             |                                 /   \            |"
PRINT "    |        _____|_____                           /_____\           |"
PRINT "    |       |           |                             |              |"
PRINT "    |       |  CASTELL  |                             |_ _ _ _ _     |"
PRINT "    |       |___________|                                      |     |"
PRINT "    |            |            ______________                   |     |"
PRINT "    |            |_ _ _ _ _ _ |            |             ______|____ |"
PRINT "    |                         | BIBLIOTECA |            |          | |"
PRINT "    |                         |____________|            |  TEMPLE  | |"
PRINT "    |                                |                  |__________| |"
PRINT "    |       _ _ _ _ _ _ _ _ _ _ _ _ _|                        |      |"
PRINT "    |      |                                                  |      |"
PRINT "    |  ____|______               __________                   |      |"
PRINT "    |  |         |               |        |                   |      |"
PRINT "    |  |  COVES  |- - - - - - - -|  PONT  |- - - - - - - - - -|      |"
PRINT "    |  |_________|               |________|                          |"
PRINT "    |                                                                |"
PRINT "    |________________________________________________________________|"
A$ = INPUT$(1)
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "             _____  _____  _____  _____  _____  .      .    "
PRINT "             |      |   |  |        |    |      |      |"
PRINT "             |      |___|  |____    |    |__    |      |"
PRINT "             |      |   |      |    |    |      |      |"
PRINT "             |____  |   |  ____|    |    |____  |____  |____"
A$ = INPUT$(1)
10 CLS
COLOR 6
PRINT ""
PRINT ""
PRINT "                    ______________"
PRINT "                  / |            | \"
PRINT "                /   |  ________  |   \"
PRINT "              /  /| |  |      |  | |\  \"
PRINT "            /  /  | |  |   1  |  | |  \  \"
PRINT "          /  /    | |  |      |  | |    \  \"
PRINT "        /    | 2  | |  |      |  | |  3 |    \"
PRINT "      /      |    | |__|______|__| |    |      \"
PRINT "      |      |    |/              \|    |      |"
PRINT "      |      |   /                  \   |      |"
PRINT "      |      | /                      \ |      |"
PRINT "      |      /                          \      |"
PRINT "      |    /                              \    |"
PRINT "      |  /                                  \  |"
PRINT "      |/______________________________________\|"
A$ = INPUT$(1)
IF A$ = "1" THEN 20
IF A$ = "2" THEN 30
IF A$ = "3" THEN 40
GOTO 10
20 CLS
PRINT ""
PRINT ""
PRINT ""
PRINT "             _______________________________________"
PRINT "           / |                                     | \"
PRINT "         /   |                                     |   \"
PRINT "       /     |    ______                           |     \"
PRINT "     /       |   |      |                          |       \"
PRINT "   /         |   |      |                          |         \"
PRINT "  |          |   |      |                          |         |"
PRINT "  |          |   |      |         _____________    |         |"
PRINT "  |          |   |      |        |\            \   |         |"
PRINT "  |          |___|______|________|__\            \_|         |"
PRINT "  |         /                    |    \____________\\        |"
PRINT "  |       /                      |    |        |   |  \      |"
PRINT "  |     /                             |            |    \    |"
PRINT "  |   /                               |            |      \  |"
PRINT "  |_/_______________________________________________________\|"
PRINT ""
PRINT "          1. PORTA              2. TAULA"
A$ = INPUT$(1)
IF A$ = "1" THEN 10
IF A$ = "2" THEN 25
GOTO 20
25 CLS
FOR T = 1 TO 10
PRINT ""
NEXT T
PRINT "                     HI HA UN PAPER"
A$ = INPUT$(1)
CLS
PRINT "     "
PRINT ""
PRINT "        _________________________________________"
PRINT "        |                              ________ |"
PRINT "        |                              |      | |"
PRINT "        |                              |      | |"
PRINT "        |    T I Q U E T               |______| |"
PRINT "        |                                       |"
PRINT "        |        P E R                          |"
PRINT "        |                                       |"
PRINT "        |   E L    G L O B U S                  |"
PRINT "        |_______________________________________|"
A$ = INPUT$(1)
A = 10
GOTO 20
30 CLS
COLOR 12
PRINT ""
PRINT ""
PRINT "                                          ________"
PRINT "                                        /          \"
PRINT "                                      /              \"
PRINT "                                      |              |"
PRINT "                                      |              |"
PRINT "                                      |              |"
PRINT "                                       \            /"
PRINT "                                         \        /"
PRINT "                                          |______|"
COLOR 6
PRINT "        ____                               |    |"
PRINT "       _||||_         ____                 |    |"
COLOR 12
PRINT "        |__|          |__|                 |    |"
COLOR 8
PRINT "         ||            ||                __|____|__"
PRINT "        /||\          /||\               |        |"
PRINT "       / || \        / || \              |        |"
PRINT "        /  \          /  \               |        |"
PRINT "       |    |        |    |              |________|"
PRINT ""
COLOR 15
PRINT "           SI TENS EL TIQUET DEL GLOBUS POTS PUJAR"
PRINT "(SI/NO)"
A$ = INPUT$(1)
IF A = 10 AND A$ = "S" THEN 50
IF A = 0 AND A$ = "N" THEN 10
IF A = 10 AND A$ = "N" THEN GOSUB 35
IF A = 0 AND A$ = "S" THEN 36
GOTO 30
35 LOCATE 1, 1
PRINT "HA NO, DON€ AIXO QUE PORTES A LA BUTXACA QUE ES?"
A$ = INPUT$(1)
RETURN
36 LOCATE 1, 1
PRINT "VEJAM ENSE¥AMEL, PUES PER DIR MENTIDES ET MATO"
A$ = INPUT$(1)
GOTO 1000
40 CLS
A$ = INPUT$(1)

COLOR 8
FOR T = 1 TO 5
PRINT " |                                            |"
NEXT T
PRINT " |                _____                       |"
PRINT " |                |   |                       |"
PRINT " |                |___|                       |"
PRINT " |                  |                         |"
PRINT " |                 /|\                        |"
PRINT " |               /  |  \                      |"
PRINT " |                  |                         |"
PRINT " |                 / \                        |"
PRINT " |               /     \                      |"
PRINT "_|______________|_______|_____________________|_______________________"
FOR T = 1 TO 2000: NEXT T
CLS
FOR T = 1 TO 5
PRINT "         |                         | "
NEXT T
PRINT "         |        _____            |"
PRINT "         |        |   |            |"
PRINT "         |        |___|            |"
PRINT "         |          |              |"
PRINT "         |         /|\             |"
PRINT "         |       /  |  \           |"
PRINT "         |          |              |"
PRINT "         |         / \             |"
PRINT "         |       /     \           |"
PRINT "_________|______|_______|__________|__________________________________"
FOR T = 1 TO 2000: NEXT T
CLS
FOR T = 1 TO 14
PRINT "                   |  |        "
NEXT T
PRINT "___________________|__|_______________________________________________"
FOR T = 1 TO 2000: NEXT T
1000  CLS
COLOR 4

PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""

PRINT "               ________     .         .    ______"
PRINT "               |            | \       |    |     \"
PRINT "               |            |   \     |    |      \"
PRINT "               |_____       |     \   |    |      |"
PRINT "               |            |       \ |    |      |"
PRINT "               |            |        \|    |      /"
PRINT "               |_______     |         |    |____/"
END
50 CLS
FOR T = 1 TO 5
PRINT ""
NEXT T
COLOR 15
PRINT "    ____    _____  ____          _____  _____  _____  _____  _____  _____"
PRINT "    |   \     |    |   \  |        |    |   |    |    |      |      |   |"
PRINT "    |___/     |    |___/  |        |    |   |    |    |___   |      |___|"
PRINT "    |   \     |    |   \  |        |    |   |    |    |      |      |   |"
PRINT "    |___/   __|__  |___/  |____  __|__  |___|    |    |____  |____  |   |"
A$ = INPUT$(1)
60 CLS
COLOR 6
PRINT "     "
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "       ______             ______           _______"
PRINT "      /     /|           /      \          |\     \"
PRINT "    /     /  |         /          \        |  \     \"
PRINT "  /_____/    |       /______________\      |    \_____\"
PRINT "  |    |     |       |              |      |     |    |"
PRINT "  |    |     |   1   |              |  2   |     |    |"
PRINT "  |    |     |       |              |      |     |    |"
PRINT "  |    |     |       |              |      |     |    |"
PRINT "  |    |    /        |              |       \    |    |"
PRINT "  |    |  /          |              |         \  |    |"
PRINT "  |____|/            |______________|           \|____|"
A$ = INPUT$(1)
IF A$ = "1" THEN 70
IF A$ = "2" THEN 80
GOTO 60
70 CLS
PRINT "                  _____________________________________________"
PRINT "                / |                                            "
PRINT "              /   |                                            "
PRINT "            /     |               _____________________________"
PRINT "          /       |             /                              "
PRINT "        /         |           /                                "
PRINT "      /           |         /                                  "
PRINT "    /             |       /____________________________________"
PRINT "   |              |       |                                    "
PRINT "   |              |       |                                    "
PRINT "   |              |_______|                                    "
PRINT "   |             /        |                                    "
PRINT "   |           /          |                                    "
PRINT "   |         /            |                                    "
PRINT "   |       /              |                                    "
PRINT "   |     /                |                                    "
PRINT "   |   /                  |                                    "
PRINT "   | /                    |____________________________________"
PRINT "   |/                                                          "
PRINT ""
PRINT "              1.GIRAR           2.TORNAR ENRRERA"
A$ = INPUT$(1)
IF A$ = "1" THEN 90
IF A$ = "2" THEN 60
GOTO 70
80 CLS
PRINT "                    "
PRINT ""
PRINT ""
PRINT ""
COLOR 8
PRINT "                     ______"
PRINT "                    /     |"
PRINT "                    \     |"
PRINT "                    /     |"
PRINT "                    \     |"
PRINT "                    /     |            CLAU DE LA PORTA DE SORTIDA"
PRINT "                    \     |"
PRINT "                  __/     |__"
PRINT "                 /          |"
PRINT "                |           |"
PRINT "                |      ____ |"
PRINT "                |      |__| |"
PRINT "                |___________|"
CLAU = 10
A$ = INPUT$(1)
GOTO 60
90 CLS
PRINT "  "
PRINT ""
PRINT "                  ________________"
PRINT "                  |              |"
PRINT "                  |  E  X  I  T  |"
PRINT "             _____|______________|____"
PRINT "             | _____________________ |"
PRINT "             | |                   | |"
PRINT "             | |                   | |"
PRINT "             | |                   | |       NESECITES LA CLAU. LA TENS (S/N)"

FOR T = 1 TO 10
PRINT "             | |                   | |"
NEXT T
PRINT "_____________|_|___________________|_|_______________________________________"
A$ = INPUT$(1)
IF A$ = "S" AND CLAU = 0 THEN 36
IF A$ = "N" AND CLAU = 10 THEN GOSUB 36
IF A$ = "S" AND CLAU = 10 THEN 95
IF A$ = "N" AND CLAU = 0 THEN 60
GOTO 90
95 CLS
PRINT ""
PRINT ""
PRINT ""
COLOR 1

PRINT "      _______  _______            ________  ________"
PRINT "      |        |     |  \      /  |         |"
PRINT "      |        |     |   \    /   |____     |_______"
PRINT "      |        |     |    \  /    |                |"
PRINT "      |______  |_____|     \/     |_______  _______|"
A$ = INPUT$(1)
100 CLS
COLOR 8
PRINT "                            /\"
PRINT "                         __/   \"
PRINT "                       /        \_____"
PRINT "                  ____/               \"
PRINT "                 /                     \________"
PRINT "          _____/                                \"
PRINT "        /                                         \"
PRINT "      /          _____                ______        \___"
PRINT "    /          /       \            /       \           \"
PRINT "   |          |          \        /          |           |"
PRINT "   |         /             \    /             \           \"
PRINT "   |         \               \/               /           |"
PRINT "   |         |               |               |            |"
PRINT "   |         |       1       |       2        \           |"
PRINT "   |         |               |                 |          |"
PRINT "   |         |               |                 |           \"
PRINT "   |         |_______________|_________________|           |"
PRINT "   |        /                                   \          |"
PRINT "   |      /                                       \        |"
PRINT "   |   _/                                          \       |"
PRINT "   | /                                                \__  |"
PRINT "   |/                                                    \_|"
A$ = INPUT$(1)
IF A$ = "1" THEN 110
IF A$ = "2" THEN 120
GOTO 100
110 CLS
PRINT "                                          _____________________"
PRINT "                                        / |                   |"
PRINT "                                      /   |      ________     |"
PRINT "                                    /     |     /       |     |"
PRINT "                                  /       |    |         \    |"
PRINT "                                /         |     \        /    |"
PRINT "______________________________/           |     /    2   \    |"
PRINT "                             |            |    |          |   |"
PRINT "        /\                   |            |    |           \  |"
PRINT "    __/   |                  |            |____|____________|_|"
PRINT "   /       \                 |           /                     "
PRINT "  |          \               |         /                       "
PRINT "  |     1    |               |       /                         "
PRINT "   \        /                |     /                           "
PRINT "   |        \                |   /                             "
PRINT "   |         |               | /                               "
PRINT "__/___________\______________|/                                "
PRINT ""
PRINT "              3.ENRRERA"
A$ = INPUT$(1)
IF A$ = "1" THEN 130
IF A$ = "2" THEN 140
IF A$ = "3" THEN 100
GOTO 110
120 CLS
PRINT " "
PRINT ""
PRINT ""
PRINT "         /|                                           |"
PRINT "       /  |                                           |"
PRINT "     /    |                                           |"
PRINT "    |     |                                           |"
PRINT "    |  2  |                                           |"
PRINT "    |     |                                           |"
PRINT "    |     |_________________            ______________|"
PRINT "    |    /                /|           /              |"
PRINT "    |  /                / /          /                |"
PRINT "    |/________________/ /          /__________________|"
PRINT "    _________________|/           |___________________"
PRINT "    |                                                 |"
PRINT "    |                                                 |"
PRINT "    |                                                 | "
PRINT "    |                                                 |"
PRINT "    |  /\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/|"
PRINT "    |/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/  |"
PRINT " "
PRINT "  NESECITES LA CAORDA LA TENS (S/N)"
A$ = INPUT$(1)
IF A$ = "S" AND CORDA = 0 THEN 36
IF A$ = "N" AND CORDA = 10 THEN GOSUB 36
IF A$ = "S" AND CORDA = 10 THEN 160
IF A$ = "N" AND CORDA = 0 THEN 100
GOTO 120
130
140
160
END

