10 CLS
GOTO 1
20 FOR t = 1 TO 10000: NEXT t
30 a = 1
35 COLOR 4
PRINT "               LES AVENTURES DE TINTIN"
PRINT "  "
PRINT "                         A"
SOUND 50, 10
FOR t = 1 TO 20000: NEXT t
SOUND 500, 10
SOUND 400, 10
SOUND 300, 10

COLOR 4
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "       0      '  00000  0      0      00000"
PRINT "       0           0    0      0      0   0"
PRINT "       0           0    0      0      00000"
PRINT "       0           0    0      0      0   0"
PRINT "       00000     00000  00000  00000  0   0"
PRINT ""
PRINT "                 0    0  00000  00000  0000   00000"
PRINT "                 0 0  0  0      0      0   0  0"
PRINT "                 0  0 0  000    0  00  00000  000"
PRINT "                 0   00  0      0   0  0  0   0"
PRINT "                 0    0  00000  00000  0   0  00000"
FOR t = 1 TO 20000: NEXT t
37 CLS
PRINT "        HISTORI      START      END"
INPUT a$
IF a$ = "h" THEN 40
IF a$ = "s" THEN 60
IF a$ = "e" THEN END
40 CLS
PRINT "                    tot comen‡a un bon dia quant est…s pasejant"
PRINT "           i veus un avi¢ que te pana, tu t'hi acostes per veure que"
PRINT "             li passa, ­ o es un avi¢ sense matricula!!!, un dels "
PRINT "               passatgers et dispara un tret i caus a terra inconcient."
PRINT ""
PRINT "           Quant et despertes et trobes a l'hospital, on hi ha els       "
PRINT "              Dupond que t'avisen que han trobat un avi¢ sense matricula                                                                                   "
PRINT "                    que s'avia estevellat a Anglaterra. Tu tambŠ hi"
PRINT "              vas , per• per que no arribis a Anglaterra, uns malfectors"
PRINT "               et paren una trampa al tren hi t'arresten, per• tu amb"
PRINT "                 la teva  astuccia, t'escapes i aconsegueixes arribar "
PRINT "               a un poble, on haur…s d'arribar fins al baixell que va cap"
PRINT "                 a Anglaterra, par• vigila amb els Dupons, perque ells"
PRINT "               tambe son el aquell poblet"
INPUT a$
IF a$ = "" THEN 37
GOTO 37
60 CLS
LOCATE 10, 23
PRINT "                          1     BECAREFUL  FOR  MRS DUPONDS"
SOUND 200, 10
SOUND 250, 10
SOUND 300, 10
SOUND 350, 10
SOUND 400, 10
SOUND 200, 10
SOUND 400, 10
SOUND 200, 10
SOUND 400, 10
SOUND 350, 10
SOUND 300, 10
SOUND 250, 10
SOUND 200, 10
SOUND 400, 10
SOUND 200, 10
SOUND 400, 10
1 CLS
SCREEN 13
VIEW (0, 0)-(300, 170), 22
LINE (0, 170)-(100, 70), 0
LINE (100, 70)-(100, 0), 0














END


